// <auto-generated />
using System;
using CourseManager.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250428005655_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CourseManager.Core.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FinishDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Platform = "Udemy",
                            State = 0,
                            Title = "Introduction to C#"
                        },
                        new
                        {
                            Id = 2,
                            FinishDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Platform = "Pluralsight",
                            State = 0,
                            Title = "Advanced .NET Development"
                        },
                        new
                        {
                            Id = 3,
                            FinishDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Platform = "LinkedIn Learning",
                            State = 2,
                            Title = "Entity Framework Core Mastery"
                        },
                        new
                        {
                            Id = 4,
                            FinishDate = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Platform = "Coursera",
                            State = 0,
                            Title = "Mastering ASP.NET Core"
                        },
                        new
                        {
                            Id = 5,
                            FinishDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Platform = "Udemy",
                            State = 0,
                            Title = "C# Design Patterns"
                        },
                        new
                        {
                            Id = 6,
                            FinishDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Platform = "Pluralsight",
                            State = 2,
                            Title = "Clean Code Principles"
                        },
                        new
                        {
                            Id = 7,
                            FinishDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Platform = "LinkedIn Learning",
                            State = 0,
                            Title = "Microservices with .NET"
                        },
                        new
                        {
                            Id = 8,
                            FinishDate = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Platform = "Udemy",
                            State = 0,
                            Title = "Blazor WebAssembly Fundamentals"
                        },
                        new
                        {
                            Id = 9,
                            FinishDate = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Platform = "Pluralsight",
                            State = 2,
                            Title = "Testing in .NET"
                        },
                        new
                        {
                            Id = 10,
                            FinishDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Platform = "Coursera",
                            State = 0,
                            Title = "Azure for .NET Developers"
                        },
                        new
                        {
                            Id = 11,
                            FinishDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Platform = "LinkedIn Learning",
                            State = 0,
                            Title = "Dependency Injection in .NET"
                        },
                        new
                        {
                            Id = 12,
                            FinishDate = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Platform = "Udemy",
                            State = 0,
                            Title = "LINQ Mastery"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
